---
title: "polar_coordinates"
author: "Sara"
date: "12/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import, warning=FALSE, message=FALSE}
library(tidyverse)
library(viridis)
library(ggdark)
```

super-simple: identity
```{r}
x <- 1:360
y <- x
ggplot() +
  geom_point(mapping = aes(x = x, y = y)) + 
  geom_point(mapping = aes(x = x + 100, y = y)) +
  geom_point(mapping = aes(x = x + 200, y = y)) +
  geom_point(mapping = aes(x = x + 300, y = y)) +
  geom_point(mapping = aes(x = x + 400, y = y)) + 
  geom_point(mapping = aes(x = x + 500, y = y)) + 
  coord_polar() + 
  theme
```

```{r}
ggplot() + 
  geom_point(mapping = aes(x = x, y = y)) + 
  geom_point(mapping = aes(x = x , y = y + 100)) +
  #geom_point(mapping = aes(x = x + 200, y = y)) +
  #geom_point(mapping = aes(x = x + 300, y = y)) +
  #geom_point(mapping = aes(x = x + 400, y = y)) + 
  #geom_point(mapping = aes(x = x + 500, y = y)) + 
  coord_polar() 
```

```{r}
a <- 2
b <- 3
theta <- seq(0,5*pi,0.01)
r <- a + b*theta
df <- data.frame(x=r*cos(theta), y=r*sin(theta)) # Cartesian coords
ggplot(df, aes(x,y)) + 
  geom_point(col='red') + 
  geom_point(mapping = aes(x=30 + r*cos(theta), y = 20 + r*sin(theta)), color='blue')
  coord_fixed()
```

```{r}
a <- 0
b <- 10
theta <- seq(0,5*pi,0.01)
r <- a + b*theta
df <- data.frame(x=r*cos(theta), y=r*sin(theta)) # Cartesian coords
ggplot(df, aes(x,y)) + 
  geom_point(col='red') + 
  #geom_point(mapping = aes(x=30 + r*cos(theta), y = 20 + r*sin(theta)), color='blue')
  coord_fixed()
```
generate the data

```{r}
a <- 0
b <- 10
theta <- seq(0,5*pi,0.07)
r <- a + b*theta
df <- tibble(x=r*cos(theta), y=r*sin(theta)) # Cartesian coords

set.seed(1111)

df <- df %>%
  mutate(rand_w = sample(8, size = n(), replace = TRUE)) %>%
  mutate(rand_alpha = sample(10, size = n(), replace = TRUE) / 10) %>%
  mutate(rand_color = sample(12, size = n(), replace = TRUE))

df <- df %>%
  mutate(x_06 = 0.6 * x) %>%
  mutate(y_06 = 0.6 * y) %>%
  mutate(x_04 = 0.4 * x) %>%
  mutate(y_04 = 0.4 * y) %>%
  mutate(x_03 = 0.3 * x) %>%
  mutate(y_03 = 0.3 * y) %>%
  mutate(x_02 = 0.24 * x) %>%
  mutate(y_02 = 0.24 * y)
```



```{r}
df %>%
  ggplot(mapping = aes(x = x,y = y)) + 
  
  # largest central spiral
  geom_jitter(mapping = aes(size = rand_w, alpha = rand_alpha, 
                            fill = factor(rand_color), color = factor(rand_color)),
              shape = 16) + 
  
  # top right spiral
  geom_point(mapping = aes(x=x_04 + 80, y = y_04 + 70,
                           color = fct_rev(factor(rand_color)),
                           alpha = rand_alpha,
                           size = sample(rand_w)*0.4),
             shape = 16) +
  
  # bottom left spiral
  geom_point(mapping = aes(x=x_06-100, y=y_06-90,
                           color = factor(sample(rand_color)),
                           alpha = sample(rand_alpha),
                           size = sample(rand_w)*0.6),
             shape = 16) +
  
  # top left spiral
  geom_point(mapping = aes(x=x_02-95, y=y_02+95,
                           color = factor(sample(rand_color)),
                           alpha = sample(rand_alpha),
                           size = sample(rand_w)*0.2),
             shape = 16) +
  
  # bottom right spiral
  geom_point(mapping = aes(x=x_03+90, y=y_03-80,
                           color = factor(sample(rand_color)),
                           alpha = sample(rand_alpha),
                           size = sample(rand_w)*0.3),
             shape = 16) +
  
  scale_color_viridis_d(option = "viridis") +
  coord_fixed() +
  #dark_theme_void() +
  theme_void() +
  theme(plot.background = element_rect(fill = 'gray85', color = "gray85")) +
  theme(legend.position = "none")# remove legend 


```



coming back to identity and polar coordinates but with different slopes
```{r}
x <- 1:100
y1 <- x
y2 <- 2*x
y3 <- 0.5 * x
```

```{r}
ggplot(mapping = aes(x = x)) + 
  geom_point(mapping = aes(y = y1)) + 
  geom_point(mapping = aes(y = y2)) +
  geom_point(mapping = aes(y = y3)) + 
  coord_polar(theta = "y")
```

meh.

something else:
```{r}
n <- 500
tibble(r = sqrt(1:n), 
       t = (1:n) * pi * (3-sqrt(5))) %>%
  ggplot(mapping = aes(x = r*cos(t), y = r * sin(t))) +
  geom_point(aes(size = (n-r), color = r),
             shape = 16) +
  scale_color_viridis_c(option = "viridis") +
  coord_equal() +
  dark_theme_void() +
  theme(legend.position = "none")
```

